#if UNITY_EDITOR

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using FMODUnity;
using UnityEditor;
using UnityEngine;

/// <summary>
/// Automatically generates FMOD event references at:
/// Assets/_Script/Audio/Generated/AudioEvent.cs
///
/// FMOD event paths are converted into nested static classes.
/// For example:
///
/// event:/Music/TitleScreen
/// event:/Atmosphere/Wind
/// event:/SFX/Player/Attack
///
/// Becomes:
///
/// AudioEvent.Music.TitleScreen
/// AudioEvent.Atmosphere.Wind
/// AudioEvent.SFX.Player.Attack
///
/// The generated values are stored as FMODUnity.EventReference objects.
/// </summary>
public static class AudioEventGenerator
{
    private const string EventPrefix = "event:/";
    private const string OutputPath = "Assets/_Script/Audio/Generated/AudioEvent.cs";

    [MenuItem("FMOD/[Custom] Generate Audio Events")]
    public static void Generate()
    {
        var events = EventManager.Events
            .Where(e => e.Path.StartsWith(EventPrefix))
            .OrderBy(e => e.Path)
            .ToList();

        if (events.Count == 0)
        {
            Debug.LogWarning("No FMOD events found.");
            return;
        }

        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// This file is automatically generated. Do not modify manually.");
        builder.AppendLine("// Please build it from menu: FMOD/[Custom] Generate Audio Events");
        builder.AppendLine();
        builder.AppendLine("using FMODUnity;");
        builder.AppendLine();
        builder.AppendLine("public static class AudioEvent");
        builder.AppendLine("{");

        var root = BuildEventTree(events);

        GenerateClasses(builder, root, 1);

        builder.AppendLine("}");

        string directory = Path.GetDirectoryName(OutputPath);

        if (!Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(OutputPath, builder.ToString());

        AssetDatabase.Refresh();

        Debug.Log(
            $"Generated {events.Count} FMOD events to {OutputPath}");
    }

    private static EventNode BuildEventTree(IEnumerable<dynamic> events)
    {
        var root = new EventNode("AudioEvent");

        foreach (var eventData in events)
        {
            string eventPath = eventData.Path;
            string[] pathParts = eventPath
                .Replace(EventPrefix, string.Empty)
                .Split('/');

            EventNode currentNode = root;

            for (int i = 0; i < pathParts.Length; i++)
            {
                string sanitizedName = SanitizeIdentifier(pathParts[i]);

                EventNode childNode = currentNode.Children
                    .FirstOrDefault(child => child.Name == sanitizedName);

                if (childNode == null)
                {
                    childNode = new EventNode(sanitizedName);
                    currentNode.Children.Add(childNode);
                }

                currentNode = childNode;

                // The last part of the path represents the actual FMOD event.
                if (i == pathParts.Length - 1)
                {
                    currentNode.IsEvent = true;
                    currentNode.EventPath = eventPath;
                    currentNode.EventGuid = eventData.Guid;
                }
            }
        }

        return root;
    }

    private static void GenerateClasses(
        StringBuilder builder,
        EventNode node,
        int indentationLevel)
    {
        string indentation = new string(' ', indentationLevel * 4);

        foreach (EventNode child in node.Children.OrderBy(child => child.Name))
        {
            if (child.IsEvent)
            {
                GenerateEventReference(builder, child, indentationLevel);
            }
            else
            {
                builder.AppendLine(
                    $"{indentation}public static class {child.Name}");
                builder.AppendLine(
                    $"{indentation}{{");

                GenerateClasses(
                    builder,
                    child,
                    indentationLevel + 1);

                builder.AppendLine(
                    $"{indentation}}}");

                builder.AppendLine();
            }
        }
    }

    private static void GenerateEventReference(
        StringBuilder builder,
        EventNode node,
        int indentationLevel)
    {
        string indentation = new string(' ', indentationLevel * 4);

        string guidString = node.EventGuid.ToString();

        builder.AppendLine(
            $"{indentation}public static readonly EventReference {node.Name} =");
        builder.AppendLine(
            $"{indentation}    new EventReference");
        builder.AppendLine(
            $"{indentation}    {{");
        builder.AppendLine(
            $"{indentation}        Guid = new FMOD.GUID(new System.Guid(\"{guidString}\")),");
        builder.AppendLine(
            $"{indentation}        Path = \"{EscapeString(node.EventPath)}\"");
        builder.AppendLine(
            $"{indentation}    }};");

        builder.AppendLine();
    }

    private static string SanitizeIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return "_Empty";
        }

        var builder = new StringBuilder();

        foreach (char character in value)
        {
            if (char.IsLetterOrDigit(character) || character == '_')
            {
                builder.Append(character);
            }
        }

        if (builder.Length == 0)
        {
            return "_Empty";
        }

        if (char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }

        string result = builder.ToString();

        if (SyntaxFacts.IsKeyword(result))
        {
            result = "_" + result;
        }

        return result;
    }

    private static string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }

    private sealed class EventNode
    {
        public string Name { get; }

        public bool IsEvent { get; set; }

        public string EventPath { get; set; }

        public Guid EventGuid { get; set; }

        public List<EventNode> Children { get; } = new();

        public EventNode(string name)
        {
            Name = name;
        }
    }

    private static class SyntaxFacts
    {
        private static readonly HashSet<string> Keywords = new()
        {
            "abstract",
            "as",
            "base",
            "bool",
            "break",
            "byte",
            "case",
            "catch",
            "char",
            "checked",
            "class",
            "const",
            "continue",
            "decimal",
            "default",
            "delegate",
            "do",
            "double",
            "else",
            "enum",
            "event",
            "explicit",
            "extern",
            "false",
            "finally",
            "fixed",
            "float",
            "for",
            "foreach",
            "goto",
            "if",
            "implicit",
            "in",
            "int",
            "interface",
            "internal",
            "is",
            "lock",
            "long",
            "namespace",
            "new",
            "null",
            "object",
            "operator",
            "out",
            "override",
            "params",
            "private",
            "protected",
            "public",
            "readonly",
            "ref",
            "return",
            "sbyte",
            "sealed",
            "short",
            "sizeof",
            "stackalloc",
            "static",
            "string",
            "struct",
            "switch",
            "this",
            "throw",
            "true",
            "try",
            "typeof",
            "uint",
            "ulong",
            "unchecked",
            "unsafe",
            "ushort",
            "using",
            "virtual",
            "void",
            "volatile",
            "while"
        };

        public static bool IsKeyword(string value)
        {
            return Keywords.Contains(value);
        }
    }
}

#endif